'use client';

/**
 * NarrativeCard — renders AI-generated narrative for the day.
 *
 * Sections (per FORTUNE_V1_PROMPTS.daily):
 *   - daily_overview  (full-width hero summary with chip line)
 *   - daily_<dim>     (5 per-dim cards with optional pull-quote takeaway)
 *   - daily_advice    (canTry + shouldHold cards)
 *
 * Per UX Refinement Sprint (locked 2026-05-15):
 *   - 今日整體 card uses white bg (.hero) — S2.E
 *   - Per-dim score chip restructured (2-line + tier dot + aria-label) — S2.F
 *   - Pull-quote takeaway above each dim narrative — S3.E + R1.7 (no italic)
 *   - Markdown bold via parseBoldSegments + JSX (no dangerouslySetInnerHTML) — R1.3
 *   - canTry/shouldHold as cards with green/amber borders + Lucide icons — S3.F
 *   - Lucide icons replace phone emojis — S2.C
 *   - ※ disclaimer reframed to plain Chinese — S3.G
 *
 * Engine-only fallback: when `narrative` is null (AI failed or engine-only
 * preview), shows a graceful placeholder + deterministic engine signals.
 */
import * as React from 'react';
import { CircleCheck, CircleSlash } from 'lucide-react';
import type {
  DailyFortuneNarrative,
  FortuneDimension,
  HeadlinerAnchor,
} from '../../lib/fortune-api';
import HeadlinerAnchorLine from './HeadlinerAnchorLine';
import { DIM_META } from './dimensions';
import { dimTierFromScore } from './labels';
import { parseBoldSegments } from './markdown';
import { useZh } from '../LanguageContext';
import styles from './NarrativeCard.module.css';

/** Phase Fortune chat — per-dim render slot for InlineAskCard wiring. */
export type FortuneDimKey = 'romance' | 'career' | 'finance' | 'travel' | 'health';

interface Props {
  narrative: DailyFortuneNarrative | null;
  dimensions: Record<FortuneDimKey, FortuneDimension>;
  headlinerSignals?: {
    chartContext: HeadlinerAnchor[];
    triggers: HeadlinerAnchor[];
  };
  /** Phase Fortune chat — optional slot rendered AFTER each dim block.
   *  Parent passes `(dimKey) => <InlineAskCard readingType="FORTUNE"
   *  sectionKey={`daily_${dimKey}`} onAsk={...} onOpenChat={...} />`
   *  to wire per-dim chat questions. Mirrors AIReadingDisplay's
   *  renderAfterSection pattern at reading/[type]/page.tsx:754. */
  renderAfterDimension?: (dimKey: FortuneDimKey) => React.ReactNode;
  /** Phase Fortune+ progressive loading: when true, narrative is still
   *  being generated by the AI (engine data is already painted). Show
   *  shimmer skeletons for prose sections instead of the «暫不可用»
   *  fallback. Resolves to false once narrative arrives OR AI failed
   *  (in which case the fallback is the right UX). */
  loading?: boolean;
  /** Phase Fortune Streaming — per-section provisional content emitted by
   *  `section_complete` SSE events. Falls back BETWEEN skeleton and full
   *  narrative: each section renders provisional text as soon as the AI
   *  finishes that section, then gets replaced with the validator-sanitized
   *  text when the `done` event fires. Per plan v2 H1 the value is already
   *  banned-phrase-stripped on the wire, so visible to the user is safe.
   *  Order: sections may arrive out of canonical order — the component
   *  renders in fixed canonical order regardless (per DIM_META + overview/advice
   *  positions). Plan v2 H5. */
  streamedSections?: Partial<DailyFortuneNarrative>;
}

/** Per-dim takeaway field key on the narrative (e.g. 'daily_romance_takeaway') */
type TakeawayKey =
  | 'daily_romance_takeaway'
  | 'daily_career_takeaway'
  | 'daily_finance_takeaway'
  | 'daily_travel_takeaway'
  | 'daily_health_takeaway';

function takeawayKeyFor(dimKey: typeof DIM_META[number]['key']): TakeawayKey {
  return `daily_${dimKey}_takeaway` as TakeawayKey;
}

/**
 * Render a string with **markdown bold** parsed into JSX <strong> segments.
 * Safe — uses React text escaping via segment values, no dangerouslySetInnerHTML.
 */
function RichText({ text }: { text: string }) {
  // Convert the raw string BEFORE bold-splitting (render-time 繁→簡 for zh-CN; no-op
  // for zh-TW / before the converter loads). Covers all prose rendered via RichText.
  const zh = useZh();
  const segments = parseBoldSegments(zh(text));
  return (
    <>
      {segments.map((seg, i) =>
        seg.type === 'bold' ? <strong key={i}>{seg.value}</strong> : <span key={i}>{seg.value}</span>,
      )}
    </>
  );
}

export default function NarrativeCard({
  narrative,
  dimensions,
  headlinerSignals,
  renderAfterDimension,
  loading = false,
  streamedSections,
}: Props) {
  // Phase Fortune Streaming: when full narrative is null but we have ANY
  // streamedSections, render in HYBRID mode — per-section content where
  // available, skeleton where pending. Layout reservation (skeletons hold
  // each section's slot in CANONICAL_ORDER) preserves the disclaimer's Y
  // position vs the full-narrative render — plan v2 H4.
  const hasStreamed =
    !narrative && !!streamedSections && Object.keys(streamedSections).length > 0;

  // Phase Fortune+ progressive loading: when neither narrative nor streamed
  // sections exist yet but `loading=true`, render the full shimmer skeleton.
  // (When sections start arriving via streaming, we transition to hybrid
  // mode automatically via `hasStreamed`.)
  if (!narrative && !hasStreamed && loading) {
    return <NarrativeSkeleton dimensions={dimensions} headlinerSignals={headlinerSignals} />;
  }

  if (!narrative && !hasStreamed) {
    return (
      <div className={styles.fallback}>
        <p className={styles.fallbackLead}>
          AI 文字解讀暫時無法產生，可能因命理師服務忙線。以下為命局層級的結構化訊號可供參考，稍後再回來即可看到完整解讀：
        </p>
        <SignalsList dimensions={dimensions} />
      </div>
    );
  }

  /** Per-section dispatch — sanitized > provisional > skeleton.
   *  Plan v2 architecture: narrative supersedes streamedSections on `done`. */
  const sectionText = (key: keyof DailyFortuneNarrative): string | null => {
    const fromFinal = narrative?.[key] as string | undefined;
    if (typeof fromFinal === 'string' && fromFinal.length > 0) return fromFinal;
    const fromStream = streamedSections?.[key] as string | undefined;
    if (typeof fromStream === 'string' && fromStream.length > 0) return fromStream;
    return null;
  };
  const adviceContent = (): DailyFortuneNarrative['daily_advice'] | null => {
    if (narrative?.daily_advice) return narrative.daily_advice;
    const fromStream = streamedSections?.daily_advice as
      | DailyFortuneNarrative['daily_advice']
      | undefined;
    return fromStream ?? null;
  };

  const overview = sectionText('daily_overview');
  const advice = adviceContent();

  // Hybrid mode: when `hasStreamed` true but `narrative` null, render
  // skeleton-per-missing-section so disclaimer Y position stays stable
  // (plan v2 H4: «disclaimer Y delta ≤ 8px» assertion).
  const isHybrid = hasStreamed && !narrative;

  return (
    <section
      className={styles.wrap}
      aria-busy={isHybrid ? 'true' : undefined}
      aria-label={isHybrid ? 'AI 解讀載入中' : undefined}
    >
      {/* Hero overview — white card bg (S2.E) */}
      <div className={styles.hero}>
        <h3 className={styles.heroTitle}>今日整體</h3>
        {/* Option 2.5 UI layer — pre-narrative anchor chip line */}
        {headlinerSignals && headlinerSignals.chartContext.length > 0 && (
          <HeadlinerAnchorLine
            chartContext={headlinerSignals.chartContext}
            triggers={headlinerSignals.triggers}
          />
        )}
        {overview ? (
          <p className={styles.heroBody}>
            <RichText text={overview} />
          </p>
        ) : (
          <div className={styles.skeletonProse}>
            <div className={styles.skeletonLine} style={{ width: '92%' }} />
            <div className={styles.skeletonLine} style={{ width: '88%' }} />
            <div className={styles.skeletonLine} style={{ width: '70%' }} />
          </div>
        )}
        {!overview && (
          <div className={styles.skeletonHint}>AI 命理師正在為您解讀今日命盤…</div>
        )}
      </div>

      {/* 5 dimensions — DIM_META iteration enforces CANONICAL_ORDER
          regardless of section arrival order (plan v2 H5). */}
      <div className={styles.dims}>
        {DIM_META.map((m) => {
          const text = sectionText(m.narrativeKey);
          const takeaway = sectionText(takeawayKeyFor(m.key));
          const dim = dimensions[m.key];
          const score = Math.max(0, Math.min(100, dim?.score ?? 50));
          const tier = dimTierFromScore(score);
          const { Icon } = m;
          return (
            <article key={m.key} className={styles.dimBlock}>
              <header className={styles.dimHeader}>
                <span className={styles.dimIcon} aria-hidden="true">
                  <Icon size={20} strokeWidth={1.8} />
                </span>
                <span className={styles.dimTitle}>{m.zh}</span>
                {dim && (
                  <span
                    className={styles.dimBadge}
                    data-tier={tier}
                    aria-label={`${m.zh}：${score}分，${dim.label}`}
                  >
                    <span className={styles.dimBadgeDot} aria-hidden="true" />
                    <span className={styles.dimBadgeScore}>{score}</span>
                    <span className={styles.dimBadgeLabel}>{dim.label}</span>
                  </span>
                )}
              </header>
              {/* Pull-quote takeaway (S3.E + R1.7 — no italic, uses left border + accent color) */}
              {takeaway && takeaway.trim() && (
                <blockquote className={styles.takeaway}>{takeaway}</blockquote>
              )}
              {text ? (
                <p className={styles.dimBody}>
                  <RichText text={text} />
                </p>
              ) : (
                // Plan v2 follow-up #3 — 4 placeholder lines (bumped from 3)
                // to match real prose's 60-100 字 average (~4-5 lines at 16px
                // on 360px mobile). 3 lines undershoots; assertion lock at
                // «disclaimer Y delta ≤ 8px» is the contract.
                <div className={styles.skeletonProse}>
                  <div className={styles.skeletonLine} style={{ width: '94%' }} />
                  <div className={styles.skeletonLine} style={{ width: '90%' }} />
                  <div className={styles.skeletonLine} style={{ width: '88%' }} />
                  <div className={styles.skeletonLine} style={{ width: '60%' }} />
                </div>
              )}
              {/* Phase Fortune chat — per-dim InlineAskCard slot.
                  Hybrid mode: only render after the dim's narrative has
                  arrived (otherwise we'd prompt users to ask about a dim
                  with no AI grounding). When all sections present, behaves
                  identical to full-narrative render.
                  Layout reservation (visibility:hidden) keeps slot height
                  consistent so disclaimer Y delta ≤ 8px (plan v2 H4). */}
              {renderAfterDimension ? (
                text ? (
                  renderAfterDimension(m.key)
                ) : (
                  <div style={{ visibility: 'hidden' }} aria-hidden="true">
                    {renderAfterDimension(m.key)}
                  </div>
                )
              ) : null}
            </article>
          );
        })}
      </div>

      {/* Advice cards (S3.F — restructured from <ul><li> to card pills) */}
      <div className={styles.adviceGrid}>
        <div className={styles.adviceCol} data-kind="canTry">
          <h4 className={styles.adviceTitle}>
            <CircleCheck size={18} strokeWidth={2} aria-hidden="true" />
            <span>今日可試試</span>
          </h4>
          {advice ? (
            <div className={styles.adviceList} role="list">
              {(advice.canTry || []).map((item, i) => (
                <div key={`ct-${i}`} className={styles.adviceItem} data-kind="canTry" role="listitem">
                  <CircleCheck size={14} strokeWidth={2} aria-hidden="true" className={styles.adviceItemIcon} />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          ) : (
            <div className={styles.skeletonProse}>
              <div className={styles.skeletonLine} style={{ width: '84%' }} />
              <div className={styles.skeletonLine} style={{ width: '72%' }} />
            </div>
          )}
        </div>
        <div className={styles.adviceCol} data-kind="shouldHold">
          <h4 className={styles.adviceTitle}>
            <CircleSlash size={18} strokeWidth={2} aria-hidden="true" />
            <span>今日宜緩</span>
          </h4>
          {advice ? (
            <div className={styles.adviceList} role="list">
              {(advice.shouldHold || []).map((item, i) => (
                <div key={`sh-${i}`} className={styles.adviceItem} data-kind="shouldHold" role="listitem">
                  <CircleSlash size={14} strokeWidth={2} aria-hidden="true" className={styles.adviceItemIcon} />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          ) : (
            <div className={styles.skeletonProse}>
              <div className={styles.skeletonLine} style={{ width: '80%' }} />
              <div className={styles.skeletonLine} style={{ width: '68%' }} />
            </div>
          )}
        </div>
      </div>

      {/* Soft-trigger disclaimer (S3.G — reframed in plain Chinese)
          Plan v2 H4: rendered in BOTH full + hybrid modes so disclaimer
          Y position never shifts when sections arrive (≤8px delta gate). */}
      <p className={styles.disclaimer}>
        ※ 今日運勢為「軟提示」— 主要受您命格、大運、流年的長期結構影響，每日只是觸發點。建議搭配其他層級綜合參考。
      </p>
    </section>
  );
}

// ============================================================
// Sub-component — narrative skeleton (progressive loading)
// ============================================================
//
// Renders shimmer placeholders for the prose sections while keeping the
// hero card structure intact (so the page layout doesn't jump when the
// real narrative arrives ~3-5s later). The chip line from headlinerSignals
// is rendered IMMEDIATELY since it's engine-derived.

function NarrativeSkeleton({
  dimensions,
  headlinerSignals,
}: {
  dimensions: Record<FortuneDimKey, FortuneDimension>;
  headlinerSignals?: { chartContext: HeadlinerAnchor[]; triggers: HeadlinerAnchor[] };
}) {
  return (
    <section className={styles.wrap} aria-busy="true" aria-label="AI 解讀載入中">
      {/* Hero overview skeleton — keep heading + chip line visible (engine data) */}
      <div className={styles.hero}>
        <h3 className={styles.heroTitle}>今日整體</h3>
        {headlinerSignals && headlinerSignals.chartContext.length > 0 && (
          <HeadlinerAnchorLine
            chartContext={headlinerSignals.chartContext}
            triggers={headlinerSignals.triggers}
          />
        )}
        <div className={styles.skeletonProse}>
          <div className={styles.skeletonLine} style={{ width: '92%' }} />
          <div className={styles.skeletonLine} style={{ width: '88%' }} />
          <div className={styles.skeletonLine} style={{ width: '70%' }} />
        </div>
        <div className={styles.skeletonHint}>AI 命理師正在為您解讀今日命盤…</div>
      </div>

      {/* 5 dim skeleton cards — show dim header + score (engine), placeholder body */}
      <div className={styles.dims}>
        {DIM_META.map((m) => {
          const dim = dimensions[m.key];
          const score = Math.max(0, Math.min(100, dim?.score ?? 50));
          const tier = dimTierFromScore(score);
          const { Icon } = m;
          return (
            <article key={m.key} className={styles.dimBlock}>
              <header className={styles.dimHeader}>
                <span className={styles.dimIcon} aria-hidden="true">
                  <Icon size={20} strokeWidth={1.8} />
                </span>
                <span className={styles.dimTitle}>{m.zh}</span>
                {dim && (
                  <span
                    className={styles.dimBadge}
                    data-tier={tier}
                    aria-label={`${m.zh}：${score}分，${dim.label}`}
                  >
                    <span className={styles.dimBadgeDot} aria-hidden="true" />
                    <span className={styles.dimBadgeScore}>{score}</span>
                    <span className={styles.dimBadgeLabel}>{dim.label}</span>
                  </span>
                )}
              </header>
              {/* Plan v2 follow-up #3 — 4 placeholder lines (was 2 in pre-
                  streaming skeleton; bumped to match real prose length and
                  keep disclaimer Y delta ≤ 8px on transition to streamed
                  sections). */}
              <div className={styles.skeletonProse}>
                <div className={styles.skeletonLine} style={{ width: '94%' }} />
                <div className={styles.skeletonLine} style={{ width: '90%' }} />
                <div className={styles.skeletonLine} style={{ width: '88%' }} />
                <div className={styles.skeletonLine} style={{ width: '60%' }} />
              </div>
              {/* Audit M3 fix — `renderAfterDimension` (per-dim InlineAskCard)
                  is DELIBERATELY omitted during skeleton. Rationale: user
                  shouldn't be prompted to ask about a dim that hasn't been
                  narrated yet — the chat-prompt CTA would invite questions
                  with no AI grounding. Chat is mounted at page level via
                  the floating button, so users can still chat during skeleton
                  state; just not through per-dim prompts. */}
            </article>
          );
        })}
      </div>

      {/* Advice skeleton — 2 columns with title visible (S3.F structure) */}
      <div className={styles.adviceGrid}>
        <div className={styles.adviceCol} data-kind="canTry">
          <h4 className={styles.adviceTitle}>
            <CircleCheck size={18} strokeWidth={2} aria-hidden="true" />
            <span>今日可試試</span>
          </h4>
          <div className={styles.skeletonProse}>
            <div className={styles.skeletonLine} style={{ width: '84%' }} />
            <div className={styles.skeletonLine} style={{ width: '72%' }} />
          </div>
        </div>
        <div className={styles.adviceCol} data-kind="shouldHold">
          <h4 className={styles.adviceTitle}>
            <CircleSlash size={18} strokeWidth={2} aria-hidden="true" />
            <span>今日宜緩</span>
          </h4>
          <div className={styles.skeletonProse}>
            <div className={styles.skeletonLine} style={{ width: '80%' }} />
            <div className={styles.skeletonLine} style={{ width: '68%' }} />
          </div>
        </div>
      </div>

      {/* Audit H4 fix — render the disclaimer in the skeleton too so the
          layout doesn't jump ~36px when the real narrative arrives. Static
          text, no skeleton styling needed (same content as main render). */}
      <p className={styles.disclaimer}>
        ※ 今日運勢為「軟提示」— 主要受您命格、大運、流年的長期結構影響，每日只是觸發點。建議搭配其他層級綜合參考。
      </p>
    </section>
  );
}

// ============================================================
// Sub-component — structured signals fallback when AI unavailable
// ============================================================

function SignalsList({
  dimensions,
}: {
  dimensions: Record<'romance' | 'career' | 'finance' | 'travel' | 'health', FortuneDimension>;
}) {
  return (
    <div className={styles.signalsList}>
      {DIM_META.map((m) => {
        const dim = dimensions[m.key];
        if (!dim) return null;
        const { Icon } = m;
        return (
          <article key={m.key} className={styles.signalsBlock}>
            <h4 className={styles.signalsTitle}>
              <Icon size={16} strokeWidth={1.8} aria-hidden="true" />
              {m.zh} · {dim.score} · {dim.label}
            </h4>
            {dim.signals.length > 0 ? (
              <ul className={styles.signalsItems}>
                {dim.signals.map((sig, i) => (
                  <li key={i}>{sig.narrative}</li>
                ))}
              </ul>
            ) : (
              <p className={styles.signalsEmpty}>今日該維度平穩，無特別動向</p>
            )}
          </article>
        );
      })}
    </div>
  );
}
